apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: book-list
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: bojana3011/book-list-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://backend-service:8000"
            - name: DANGEROUSLY_DISABLE_HOST_CHECK
              value: "true"